version: "3.8"

services:
  api:
    build: api
    ports:
      - "80:80"
    networks:
      - api

  jupyter:
    build:
      context: .
      dockerfile: jupyter/Dockerfile
    ports:
      - 8888:8888
    volumes:
      - type: bind
        source: ./jupyter/notebooks
        target: /home/jovyan/notebooks
    env_file: .env
    environment:
      - JUPYTER_ENABLE_LAB=yes
    depends_on:
      - elasticsearch
    networks:
      - elasticsearch

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.2
    networks:
      - elasticsearch
    volumes:
      - type: bind
        source: ./data/elasticsearch
        target: /usr/share/elasticsearch/data
    ports:
      - 9200:9200
    env_file: .env
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: -Xms3g -Xmx3g

  kibana:
    image: docker.elastic.co/kibana/kibana:7.13.2
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
    networks:
      - elasticsearch
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200

  process_images:
    build: process_images
    depends_on:
      - elasticsearch
      - api
    networks:
      - elasticsearch
      - api

networks:
  elasticsearch:
  api:
